### PR TITLE
profile demos

### PR DESCRIPTION
**Pull request by jywarren**
Just stubbing some ready-made demos for each profile -- just added Browser to start with, though I know this isn't ready until the Browser profile works. (does it work yet, but just poorly, or not at all?)

I'd like also to add buttons on each demo linking to the other demos, so you can easily swap the current demo state. 

I've just used GET params to switch the profile, but it doesn't seem to be loading. I don't have more time now to work on this, but this could be a pretty low-maintenance way to have multiple demos off the same code.

### CODE REVIEW

**Comment by rmeister** [comment]
Very good idea! And it did work for me, so we can merge.

**Comment by jywarren** [comment]
done!

**Comment by rmeister** [comment]
Cool, I'll update the gh-pages

**Comment by jywarren** [comment]
oh oops, did it already! was eager to see. :-)

**Pull request merged**
