### PR TITLE
Enhanced Octave decoder and decoding explanation

### PR DESCRIPTION
**Pull request by rmeister**
Finally the decoder written in Octave works. I added a longer description about the demodulation and decoding process.

### CODE REVIEW

**Comment by rmeister** [comment]
Also there's a synchronization error calculation in a [Google sheet](https://docs.google.com/spreadsheets/d/1FgNwMYz1BY7YfkxdFYrwCYVjnjbC_Py1jo3o2qMi5ug/edit?usp=sharing). I'm not sure what's the best way to include it. Any thoughts on this?

**Comment by jywarren** [comment]
Hmm, is the synchronization error calculation based on empirically collected values, or where's it sourced from? You could include it as a JSON file, perhaps... but not sure! 

Ready for merge?

**Comment by rmeister** [comment]
The calculation is completely based on the SoftModem implementation. So in the sheet the values in capitals are calculated in the same manner as in the code. Are the calculations visible when clicking on the individual cells? Don't know if you can see this, as I only allowed viewing the file and not modification.

I could make a markdown table out of the results, but then the formulas get lost :confounded: 

Not yet ready, I'll add another image and move the images into a subfolder.

**Comment by jywarren** [comment]
Ah, yes, the calcs are:

    =ROUNDDOWN(B22;0)/(16000000/B8)

What's your intent with the spreadsheet, just as a utility for devs working
on the encoder/decoder? How is its use distinguished from the use of the
code version, if they're the same? Thanks, just trying to sync with what
you're thinking.

**Comment by rmeister** [comment]
I started making this sheet because there were different offsets for different parameters. This made me curious, as there was no hint in the code. Just four sets of parameters to chose. 
I wanted to show which parameter works best. I think this is important for everyone who wants to use SoftModem.

**Comment by rmeister** [comment]
Now ready :smile:

**Comment by jywarren** [comment]
Before merging this, I want to request that you add the images (at least) to an `.npmignore` file, so they don't have to be pulled in if this package is included via npm or browserify. 

Also - perhaps soon, what do you think about some tests? Perhaps in Jasmine, or another test framework of your choice?

**Comment by rmeister** [comment]
Ah, that makes sense.

Yeah, I imagine a test that automatically reads a recorded signal and feeds the decoder. Does this match your conception of tests?
As I've never written tests in JavaScript before, I would rely on your judgment regarding the framework.

**Comment by jywarren** [comment]
Are you familiar with unit vs. integration testing? My thought was that if
your code is well modularized, we can unit test each piece. For example, we
could feed an audio file through and see, for unit testing.

One issue is that we won't generate precisely the same audio when we
re-encode it. Then for integration testing, we'd test the whole library via
the constructor.

I use Jasmine in many other codebases, so you could look at, for example,
this folder: https://github.com/bevacqua/banksy/tree/master/spec/

it uses jasmine (see its package.json) and has some simple tests in it.
Want to give it a try?

**Comment by rmeister** [comment]
Well I'v heard these terms and also have written some unit tests before, but I would not say I'm an expert in testing. Though I'll try my best :)

Is this really a problem? If we encode some data and the decoder corectly detects it, why re-encode? 

Thanks for sharing the example, I'll have a look at Jasmine.

**Comment by jywarren** [comment]
No, not really a problem, just starting to think through how the tests are
written.

Cool!

**Comment by rmeister** [comment]
Anything missing here?

**Comment by jywarren** [comment]
All good, thanks! Sorry, had forgotten to check again and actually merge.

**Comment by rmeister** [comment]
Perfect, Thanks :)

**Pull request merged**
