### PR TITLE
Setter for profiles

### PR DESCRIPTION
**Pull request by rmeister**
Buttons for the demo still missing, will be handed in later.

### CODE REVIEW

**Comment by rmeister** [comment]
profiles

I admit that I'm not a css wizard, styling proposals are very welcome.

**Comment by jywarren** [comment]
Oh, this looks fine, no worries. Does it refresh the page or reload the
library? Great work!

**Comment by rmeister** [comment]
No page refresh, just reinitializes and calculates some parameters.

**Comment by jywarren** [comment]
This looks great;  do you think #41 would pass if rebased on top of this? 

Also you mentioned not tested on the decoder yet but I see decoder changes; is this ready for merge?

**Comment by rmeister** [comment]
With the changes commented in #41 it will pass.

Tested with hardware today, ready for merge :)

**Comment by jywarren** [comment]
I get some long output (looks like a profile object) as output during `npm test` -- is there a `console.log` we could comment out?

**Comment by jywarren** [comment]
Also, shall I make a new release now? v0.1.2?

**Comment by rmeister** [comment]
Yes a new release would be great.

**Comment by jywarren** [comment]
OK, done -- v0.1.2!

**Pull request merged**
