### PR TITLE
Added "pics" folder to store reference images, and modified README to explain 'linear gauge' and 'dial' visualizations.

### PR DESCRIPTION
**Pull request by dwblair**

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, I'm seeing some merge conflicts... Is this supposed to come after the other PRs?

**Comment by dwblair** [comment]
Ah ... I dunno what I'm doing :)

I think maybe i edited an index.html file a little, one that had been pull in via a previous PR?  Let me read up on the git process and figure out what the heck I'm doing ...

**Comment by jywarren** [comment]
Ok cool! Check out "GitHub flow" -- and also it's helpful to look at the
"changed files" tab on each PR to see the combined changes from a set of
commits. Thanks!!

**Comment by dwblair** [comment]
Okay, this might not be the most elegant way, but for my simple brain I
just did the 'reset' thing like you'd suggested before and pulled from the
publiclab master repo ... so maybe you can just close any PR's from me that
have arrived since?

Now I'll tread a bit more carefully when submitting PRs, and hope to ensure
they don't create merge conflicts :)

**Comment by jywarren** [comment]
Ooh, careful -- you're editing to master, instead of a feature branch, so you're combining your distinct features into a single pull request. We'd hope to see:

`dwblair  wants to merge 23 commits into publiclab:master from dwblair:feature-branch` and not `dwblair:master` -- but I think your work is separable; could you break out the dial/gauge work into one PR based on the latest master, and another PR of just the error-correction code?

**Comment by dwblair** [comment]
Ahhh ... I'm beginning to get it now, I think.  Thanks.  Can definitely
break out the dial / gauge work, and the CRC work, as you suggest here ...
and submit PRs from feature branches ...

**Comment by jywarren** [comment]
awesome, MUCH appreciated, as I know this is a little obscure!

**Pull request closed without merging**
