### PR TITLE
public api for options hash

### PR DESCRIPTION
**Pull request by jywarren**
Really simple change to expose `options` object as a public API; this makes testing profile changes easier (which we should do). I don't know if this API is settable -- just gettable for now, depending on how the encoder/decoder work.

### CODE REVIEW

**Comment by jywarren** [comment]
If this looks good to you, I'd like to merge it, @rmeister -- but was hoping for some clarification on the questions above. Thanks!

**Comment by rmeister** [comment]
Sure you can merge.

Setting the options will not work though. There are Float32Array's in the encoder and decoder that have to be reinitialized and filled with the new parameters.

**Comment by jywarren** [comment]
Would moving the encoder constructor into an `setOptions(opts)` method allow us to reparse the options object? I see that for the Decoder, init is triggered by an listener, but we could in theory put this entire block in a `setOptions(opts)` method:

https://github.com/publiclab/webjack/blob/master/src/webjack.js#L28-L73

**Comment by jywarren** [comment]
If that works, I'm happy to make the changes and run some unit tests of `setOptions` changing encoder/decoder settings. Is there a strong reason (besides some memory and code containment) to keep encoder and decoder as private? Exposing them would help us test, though it's not a huge benefit. 

Theoretical question -- I'm not familiar with anyone doing this, but I could imagine using a `testing` options flag to expose everything publicly for testing, while in normal use they'd be private. I guess it violates "test external APIs" though so maybe never mind.

**Pull request merged**
