### PR TITLE
Encoder

### PR DESCRIPTION
**Pull request by rmeister**
Now supports sampling rates larger than 44.1kHz. Uses linear upsampling, taken from here: [https://github.com/taisel/XAudioJS/blob/master/resampler.js](https://github.com/taisel/XAudioJS/blob/master/resampler.js).
Not clean, but working. Cleanup will follow.

### CODE REVIEW

**Comment by jywarren** [comment]
Shall I wait on merging? By the way, it may be a good idea to rebase your own changes on top of master -- I see a lot of "merge branch 'master' into encoder" commits, and if you rebase, you can avoid this and maintain a cleaner commit history. I believe you can in this case `git rebase --interactive master` the entire stack, and squash or "f" the merge commits at least. 

Thanks, exciting to see this!!

**Comment by jywarren** [comment]
Also, I'm only testing publiclab/master here, but I got this odd error:

```js
webjack.js:99 Uncaught RangeError: Source is too largegenerateBitBuffers @ webjack.js:99init @ webjack.js:102Class @ webjack.js:60init @ webjack.js:184Class @ webjack.js:60(anonymous function) @ (index):33fire @ jquery.js:3187fireWith @ jquery.js:3317ready @ jquery.js:3536completed @ jquery.js:3552
```

on a ChromeBook (ARM) -- I wonder if this is still the case with your more recent commits? Just a heads up as I may be less available in the coming days.

**Comment by rmeister** [comment]
This should not occur with the latest commit. Is there any output like
"target sample rate: ..." before the error?

Thanks for the rebase hint :)
Am 21.06.2016 10:20 vorm. schrieb "Jeffrey Warren" <notifications@github.com

**Comment by rmeister** [comment]
Ready for merge.

Included a hint to the original resampler:
```
// JavaScript Audio Resampler by Grant Galitz
// from https://github.com/taisel/XAudioJS/blob/master/resampler.js
// simplified for single channel usage
```

**Pull request merged**
