### PR TITLE
Decoder

### PR DESCRIPTION
**Pull request by rmeister**
The decoder works...somehow. Error rate atm quite high, see picture below:

hodor

### CODE REVIEW

**Comment by rmeister** [comment]
Tests fail, because it is not merged with decoder-tests branch yet.

**Comment by jywarren** [comment]
Hi, @rmeister - any updates?

**Comment by rmeister** [comment]
Not yet. Quality really depends on the right volume level.

I'd like to debug on the phone, but Chrome does not permit access to the microphone for non-https sites. Firefox permits mic usage, but is there something like remote debugging in Firefox? I'd propose to merge and debug via gh-pages this time. Enhancements will come in the next PR.

**Comment by jywarren** [comment]
aha, well, you can debug in your own `gh-pages` branch, which would then
show up at https://rmesiter.github.io/webjack/examples/ -- and/or you could
use node to host a local https server?
https://www.npmjs.com/package/http-server

**Comment by rmeister** [comment]
ah true, I'll try that!

**Comment by rmeister** [comment]
Bower as well?

**Comment by jywarren** [comment]
Yes! :-)

**Comment by rmeister** [comment]
Oops, that last one was not intended... well now it is one PR :)

**Comment by jywarren** [comment]
Hmm, checks have failed - can you take a look? Thanks!

**Comment by rmeister** [comment]
Forgot to build :laughing: 

One test is still failing. It is because the preamble is somehow longer at that recording and therefore will not be detected correctly. This is just a matter of optimizing a parameter. Rest of the tests is passing.

**Comment by jywarren** [comment]
Ok great. Should I merge or are you filing a follow-up fix?

**Comment by rmeister** [comment]
You can merge :)

**Comment by jywarren** [comment]
Ok, doing so, but do you think you can push a fix or comment out that test fairly soon? Thanks.

**Comment by jywarren** [comment]
Actually I says I can't from a phone, interesting: 

> Pull requests that have a failing status can’t be merged from a phone.

I'll merge at my laptop in about an hour.

**Comment by rmeister** [comment]
Should not fail this time :D

**Comment by jywarren** [comment]
Super! I'll do the npm publish shortly

**Comment by rmeister** [comment]
Cool, thanks!

**Comment by jywarren** [comment]
Published: https://www.npmjs.com/package/webjack

Also in bower, though they don't have a permalinkable page for it (and/or their cache hasn't updated yet).

I've also made you a repo collaborator so you'll have write/push permissions (use wisely!) and are listed on the npmjs.com page.

**Pull request merged**
