### PR TITLE
try migrating to GitHub Actions from Travis for CI

### PR DESCRIPTION
**Pull request by aliciapaz**
Based on similar work on: https://github.com/publiclab/spectral-workbench.js/pull/207 and https://github.com/publiclab/image-sequencer/pull/1783 

Let's see how this goes!

### CODE REVIEW

**Comment by aliciapaz** [comment]
For some reason, when I open a PR from my feature branch, the workflow is not triggered. However, if I open a PR on my own forked repository, the GH action works: 
https://github.com/aliciapaz/webjack/pull/1 
@jywarren what do you think might be wrong? 
On the other hand, this made me realize I can test the workflows in my forked repository before I open the PR in the base repo :)

**Comment by jywarren** [comment]
Aha! Yes I believe this is a security limitation. I believe we can get you
credentials to open on publiclab's as well!

**Comment by jywarren** [comment]
Hi Alicia - just wondering if we could sync up in Gitter or another channel? Thanks!

I checked permissions and i know there's something about it that's a bit hard to remember -- if I make you a contributor on this repo, you should be able to open it from a branch of publiclab/webjack, not aliciapaz/webjack, and i think that will help? But i'm not 100% sure.

This looks all good, for starters:

image

**Comment by jywarren** [comment]
This document is strangely unhelpful: https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization

**Comment by jywarren** [comment]
So glad to see you're digging into this!

**Comment by jywarren** [comment]
Moving to https://github.com/publiclab/webjack/pull/191 🎉

**Pull request closed without merging**
