### PR TITLE
Encoder implemented

### PR DESCRIPTION
**Pull request by rmeister**
As the title says. Borrowed some code from here: [https://github.com/NeoCat/FSK-Serial-Generator-in-JavaScript](https://github.com/NeoCat/FSK-Serial-Generator-in-JavaScript)

The encoder is already wired into the demo, so a click on 'Send' should produce awful sounds. 

Correctness of the generated signal was verified with this Arduino sketch:
```
#include <SoftModem.h>
SoftModem modem = SoftModem();

void setup() {
  Serial.begin(115200);
  Serial.println("Booting");
  delay(100);
  modem.begin();
}

void loop() {
  while(modem.available()){
    int c = modem.read();
    if(isprint(c)){
      Serial.print((char)c);
    }
    else{
      Serial.print("(");
      Serial.print(c,HEX);
      Serial.println(")");      
    }
  }
  if(Serial.available()){
    modem.write(0xff);
    while(Serial.available()){
      char c = Serial.read();
      modem.write(c);
    }
  }
}
```

### CODE REVIEW

**Comment by rmeister** [comment]
That was fast, thanks :smiley:

**Comment by jywarren** [comment]
I merged it into the gh-pages branch too, but is the demo hooked up? I
couldn't get it to make noise in Firefox for Android.  Exciting though!!

**Comment by rmeister** [comment]
Oh, you are right, it does not seem to work for mobile browsers. Working on it!

**Comment by rmeister** [comment]
The sampling rate is the problem here. It is given by the hardware/OS and the Web Audio API does not allow to choose the rate. This is pretty bad, as other sampling rates make transmission much more error-prone or even impossible. I'm not sure how to deal with this. Maybe we can find a combination of frequencies for which the errors don't become to large.

**Comment by jywarren** [comment]
Oh wow, that does sound troubling. I wonder if we could ask about this on
other lists or audio projects issue trackers for ideas. Not to mention on
the plots-dev list.

**Pull request merged**
