### PR TITLE
Adding rickshaw.js plotting functionality

### PR DESCRIPTION
**Pull request by dwblair**
Used in 'plotter.html'

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Don - do you think you could move the `rickshaw` dependencies into a folder in `/examples/lib/rickshaw/`? That way they're not mixed up with the actual module's source? Thanks!

**Comment by dwblair** [comment]
Yes, def!  Will refactor that asap --

should lib/ maybe be located even deeper in the directory?  e.g. my
plotting example would be located in:

/examples/plotter/

which would contain:

plotter.html
and
lib/rickshaw

maybe?

that way people could easily sort out which examples depended on which
libraries?

i could e.g. imagine making another example folder that doesn't use
rickshaw, but requires some other library ...

anyway, on bus now but will refactor asap!

**Comment by jywarren** [comment]
sure -- github pages actually will take the filename (minus extension) or
the containing folder name (using the index.html inside) as a valid URL.
both:

http://publiclab.github.io/webjack/examples/index
http://publiclab.github.io/webjack/examples/

load `/examples/indexindex.hmtl`

so that sounds good to me, yes! `
http://publiclab.github.io/webjack/examples/plotter/`, perfect!

Thanks, Don, you're the best! What rapid-fire productivity :-)

**Comment by dwblair** [comment]
Oh, perfect!

How does this best work -- you reject my PR, and then I submit a new PR
when I've moved the code around appropriate?  Excited to learn the github
workflow, sorry I'm still new to it :)

Exciting!

**Comment by jywarren** [comment]
We can do that, but if you just move it and add one more commit, I'm going to squash all the commits when I merge anyways so it's not a big deal. Thanks!

**Comment by jywarren** [comment]
Hi, Don - so it may make more sense for you (in general, but we don't have to do it for this one) to do development in a feature branch, so that you can always rebase against your own local copy of master. That is, your local master ought to be the same as the publiclab master, so you can more easily ensure that your changes are always in relation to the latest version (with, say, a rebase). This flow is covered here: https://publiclab.org/wiki/contributing-to-public-lab-software

Anyhow I think all is good, but before pulling from publiclab/master, you'll want to rewind your branch to a363663 -- with `git reset --hard a363663` (don't worry, all your changes are now saved in #46), and then `git pull https://github.com/publiclab/webjack.git master` to get all the integrated changes.

Hope that makes sense! I'm closing this PR now in favor of the reformatted #46.

**Comment by jywarren** [comment]
Also you can review my additions here: https://github.com/publiclab/webjack/pull/46/commits/153a55c32c01b364d31a09ae948a91557b86eb69

Thanks! I added a README entry too: https://github.com/publiclab/webjack#plotting

**Comment by dwblair** [comment]
Cool!  Makes sense -- the hard reset + pull worked smoothly ... and I'll
plan to work do new dev in 'feature' branches, as you suggest ... fun to
learn how the professionals do it! :)  Thanks thanks ...

**Pull request closed without merging**
