### PR TITLE
Enhanced example page

### PR DESCRIPTION
**Pull request by rmeister**
I filled in some css and added a submit button.

Also now there is a hint in the textarea saying one can enter commands like 'help'. This is ment for an example Arduino sketch, which implements these commands.

### CODE REVIEW

**Comment by rmeister** [comment]
demo_page

**Comment by jywarren** [comment]
ooh, this looks great. Should I merge pull #1 first, then this?

**Comment by rmeister** [comment]
yes please :smile:

**Comment by jywarren** [comment]
Can you rebase this and I'll merge in the morning? Thanks!!! Very excited. Curious how far you are on transmit and receive.

**Comment by jywarren** [comment]
Ah, odd. I squashed the other commits and now this conflicts. But I bet it'll rebase cleanly.

**Comment by jywarren** [comment]
Hmm, maybe I misunderstood - this doesn't rebase cleanly. Should I have pulled in this one and not the other? I'm happy to backtrack if need be to resolve this; the repo is almost brand new. Just give me a heads up, thanks!

**Comment by rmeister** [comment]
Er, I'm a little confused now. GitHub says there are no conflicts.
Seems it was a bad idea from me to change Class.js directly on the GitHub page.

**Comment by jywarren** [comment]
I found that when i run:

````
git checkout -b rmeister-enhanced-example-page master
git pull https://github.com/rmeister/webjack.git enhanced-example-page
````

It looks good, but when i then run `git rebase master` to ensure that the changes are FF, it shows a bunch of conflicts. Let me check the git log commit order... it should be OK but maybe it's just a bit non-linear or something?

**Comment by jywarren** [comment]
Ah, i think it's because you rebased a bunch of stuff after 2152097c212495e8f92dcedf61416816c10fc972, and this maybe isn't staged on top of that rebase, even though it didn't change the order of diffs? Just a theory. 

merging this is fast-forward, so I think we're all good. Merging, thanks!

**Comment by rmeister** [comment]
Great, thanks Jeff!

**Comment by jywarren** [comment]
Yeah i think we got a little nonlinear -- check it out: https://github.com/publiclab/webjack/network

no harm though. Let's try to rebase each change on top of the latest master though, it keeps the history clean. Thanks!

**Comment by jywarren** [comment]
Also, i committed the dependencies into a 'gh-pages' branch, which means we can have a live demo hosted by github pages: http://publiclab.github.io/webjack/examples/

cool!

**Comment by jywarren** [comment]
the dependencies will never be merged into master, but it's a good way to keep a demo of the project online for people to try out.

**Comment by rmeister** [comment]
wow nice, thanks :)

**Pull request merged**
