### PR TITLE
basic empty test suite in tape

### PR DESCRIPTION
**Pull request by jywarren**
Test run to see if TravisCI will pick it my config file. Run tests with `npm test` -- read more about tape here: https://ponyfoo.com/articles/testing-javascript-modules-with-tape

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @rmeister - I've added one really basic (true == true) test using tape, which is nice and minimal; take a look and give it a try! I also set up continuous integration, so PRs will have tests run automatically now, although of course they're only as good as the tests we write. 

https://travis-ci.org/publiclab/webjack - shows all recent builds.

**Comment by jywarren** [comment]
I'm ready to merge it, though I think it should have a "Testing" session of the README is a good idea, and maybe a "passing" badge, as in this readme: https://github.com/publiclab/spectral-workbench.js#spectral-workbenchjs

**Comment by jywarren** [comment]
Great, shall I merge?

**Comment by rmeister** [comment]
Yes :)

**Comment by jywarren** [comment]
Haha, great, especially since it clearly passes all tests :-P

**Comment by jywarren** [comment]
I figured you could load sample audio data from the `/test/fixtures/` directory, too.

**Comment by rmeister** [comment]
That's really great, so I can record some files and write tests for the decoder, before implementing the decoder itself.

**Comment by jywarren** [comment]
I'm eager to see it! Great work.

**Pull request merged**
