### PR TITLE
decoder test suite, recordings, CI badge

### PR DESCRIPTION
**Pull request by rmeister**
Tests failing, decoder not implemented yet.

### CODE REVIEW

**Comment by rmeister** [comment]
Not sure how we can test WebJack.Connection. It currently needs the Web Audio API, which is not available in node. Had no luck with [https://github.com/sebpiq/node-web-audio-api](https://github.com/sebpiq/node-web-audio-api).

**Comment by jywarren** [comment]
For now you could have audioCtx set with a parameter and a fallback default, like:

    var audioCtx = options.audioCtx || new AudioContext();

And pass it a mocked version of the web audio api that implements things like audioCtx.createMediaStreamSource() and returns mock testing values... would that work?

**Comment by rmeister** [comment]
Ah right :) mocked it

**Comment by rmeister** [comment]
Changes integrated into #9

**Pull request closed without merging**
