### PR TITLE
Fix for use with webjack-firmata

### PR DESCRIPTION
**Pull request by rmeister**
Also fixes concurrently playing audio, that messed up the sent signal before.

### CODE REVIEW

**Comment by rmeister** [comment]
Maybe time for a new release? Cause the demo of publiclab/webjack-firmata#1 will not run correctly otherwise.

**Comment by jywarren** [comment]
sure, are you able to do it? For npm you update package.json and I can run
"npm publish" and for bower you just create the release in Github with a
v0.0.0 version number. Are you familiar with semver conventions? semver.org

**Comment by rmeister** [comment]
I'd say thats a push to 0.1.1?

**Comment by rmeister** [comment]
Err, I ment 0.1.0 :sweat_smile:

**Comment by jywarren** [comment]
Great, releasing now

**Comment by jywarren** [comment]
oh but you put in 0.1.1... well, we shouldn't go backwards. That's fine, I renamed it in the github release too. v0.1.1 it is!

**Comment by rmeister** [comment]
Yeah sorry, that was not well thought from me.

**Comment by jywarren** [comment]
no problem!

**Comment by rmeister** [comment]
Actually I created the release on GitHub and edited it afterwards to 0.1.0
:laughing:

Am 29.07.2016 9:43 nachm. schrieb "Jeffrey Warren" <notifications@github.com

**Pull request merged**
