### PR TITLE
Minor UI changes & example sketches

### PR DESCRIPTION
**Pull request by rmeister**
+ ignoring certificates used while local development

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, love the provided sample sketches. Great idea.

**Comment by rmeister** [comment]
I have one more that reads and reports the internal temperature of the ATmega328, coming soon.

**Comment by rmeister** [comment]
Let's merge? (the other PR's as well)

**Comment by jywarren** [comment]
Please go ahead!

**Pull request merged**
