### PR TITLE
Demo of CRC8 functionality; includes CRC8 Arduino library. 

### PR DESCRIPTION
**Pull request by dwblair**
I'm including a description of the use of the CRC8 functionality in a README file in examples/crc8 folder.  This can be copied / inserted directly into the main webjack/README.md -- but I'm a little timid about messing things up :)

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, this looks great -- did you source some crc8 code from anywhere you could reference in the header of that file?

The crc8.js code is also nice and simple! I'd like to figure out how to incorporate it more closely into webjack -- @rmeister, any thoughts on this? 

This would also let us write some tests for the crc8.js code; what would be a basic way to test it -- run some test data through, pass bad data and ensure it does not transcribe the bad data?

I think that means the crc8 lib would need some kind of method like `.parse(msg, checksum)` which returns only good data... thoughts?

**Comment by dwblair** [comment]
Cool!

-- Re: attribution for code (on Arduino / C++ side and on Javascript side), that's in the last sentence of the README ...

-- Eep. Just noticed that I broke the link structure in index.html when simplifying the directory structure at the last minute before committing.  

Should I close this pull request, fix it, and open a new PR?  

Great ideas re: refactoring and testing.

**Comment by jywarren** [comment]
(oh, missed that in the README, thanks!)

Since this PR is in its own named branch, you can just keep adding commits
to it. At the end we'll either ask you to squash them in a rebase, or just
let Github do it for us. That helps keep a history of our progress right
until we're ready to merge. Thanks!

We could continue to work on it in the /examples/ folder, as we develop
more self-contained crc8.js module, and when it's ready to be plugged into
the codebase with a test that's as simple as a one-liner --
`expect(crc8.parse('myerror','checksum')).toBe('')` or something, we can
move it into `/src/` -- how's that sound?

**Comment by dwblair** [comment]
Ah, cooool -- nice that I can just keep committing into the same PR!  The links are fixed now!

Just to bring it up:  the way I've implemented things, I'm using a '%' as a 'separation character between the message from the checksum, so that I  end up sending  'message%checksum' via SoftModem from the Arduino to WebJack.  On the Arduino library side, I've allowed the coder to specify the separation s character.  It might be good to write that same functionality into the Javascript side, too (maybe a different character or sequence of characters would be better;  or one could even imagine it as a field in a JSON packet).

The integration path forward you suggest sounds great to me!

**Comment by jywarren** [comment]
saw a new update -- how's this doing? Close to ready to merge in? We should make an issue for the test outlined above, as a note to future selves. 

Also, if you're free tonight, want to go to HQ?

**Comment by jywarren** [comment]
Just read through this carefully and it looks good; does it work to your satisfaction? Shall I merge it in? Thanks, Don!

**Comment by dwblair** [comment]
Hello sir! Hah sorry for the delayed reply -- I think everything's working,
so I think merging would be fine, yes!

**Comment by jywarren** [comment]
Great, merging now. Could you open a new issue specifying the next steps of integrating error correction into the source itself and writing tests? (As above)

**Pull request merged**
